### ISSUE TITLE
"text" in nullItemText

### ISSUE THREAD

**Issue by ebalders** [programcsharp/griddly#65]
Entering any text other than "" in the nullItemText parameter for filters(at least FilterList) causes the grid to refresh when selecting certain elements outside the grid. 

`.Column(c => c.Category, "Category", filter: x => x.FilterReference(ReferenceType.QueryCategory, field: "categories", nullItemText: "test"))`

You can repro in M3 by going to /Reporting/Queries and clicking the 2nd level menu item "Queries".

You may need to test in an NBF branch as we have removed the test from the grid in products branches.

**Comment by ithielnor** [comment]
This only occurs in Firefox.

**Comment by ithielnor** [comment]
I cannot reproduce this in the griddly project. It also does not occur in M3 if I use FilterList instead of FilterReference.

**Comment by ithielnor** [comment]
Nevermind. I found a repro in Griddly.

`filter: x => x.FilterList(new List<SelectListItem>(), defaultSelectAll: true, nullItemText: "(none)")`

Apparently both settings must be enabled to cause this in firefox.

**Comment by ithielnor** [comment]
`nullItemText` is not part of the cause. It occurs with the following too:

`x.FilterList(new List<SelectListItem>() { new SelectListItem() { Text = "Blah", Value = "0" } }, defaultSelectAll: true)`
