### ISSUE TITLE
Exclude from export option on columns

### ISSUE THREAD

**Issue by ghhtimsgh1970** [programcsharp/griddly#76]
IsExportOnly is nice but I have a column that I want to **exclude** from export.  For instance, an Actions column that has buttons or other UI related grid stuff.  That's being exported out to Excel.  I'd change IsExportOnly to something like ExportType.Both, ExportOnly, ViewOnly

**Comment by programcsharp** [comment]
Resolved by c89b88890f58832184f95de96666f3ebacd74ba8.
